name: mvc1api
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Actualización de la dependencia http a una versión más reciente
  http: ^1.2.2

  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+3  # Asegúrate de usar la última versión disponible

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
